<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeLogo	   = $objectManager->get('Magento\Theme\Block\Html\Header\Logo');
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('homepage/og/image');
?>

<?php if ($conf){ ?>
    <meta property="og:image" content="<?= $conf; ?>"/>
<?php }else{ ?>
    <meta property="og:image" content="<?= $storeLogo->getLogoSrc(); ?>"/>
<?php }?>
